export 'account_item.dart';
export 'back_button_widget.dart';
export 'background_shapes.dart';
export 'basket_item.dart';
export 'custom_scroll_behavior.dart';
export 'customer_agent_widget.dart';
export 'detail_slider_widget/detail_slider_container.dart';
export 'detail_slider_widget/detail_slider_item.dart';
export 'detail_slider_widget/detail_slider_widget.dart';
export 'from_message_bubble.dart';
export 'global_widget.dart';
export 'home_slider_item.dart';
export 'horizontal_card.dart';
export 'loading_bar.dart';
export 'my_button.dart';
export 'my_progress_button.dart';
export 'my_slide_action.dart';
export 'my_text_field.dart';
export 'my_tool_bar.dart';
export 'new_message_notify.dart';
export 'no_network_flare.dart';
export 'not_found_flare.dart';
export 'not_found_widget.dart';
export 'number_formatter.dart';
export 'pay_check_widget.dart';
export 'progress_button.dart';
export 'rating_bar.dart';
export 'server_failure_flare.dart';
export 'title_details_tab.dart';
export 'title_selector.dart';
export 'user_message_bubble.dart';
export 'vertical_card.dart';
export 'vertical_card_support.dart';
export 'warning_bar.dart';

int bgColor = 0xffA2DE96;
int btnColor = 0xff3CA59E;
int txfColor = 0xff3CA59E;
int icoColor = 0xff6E717A;
